# Generated by Django 6.0.3 on 2026-06-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('price', models.CharField(max_length=20)),
                ('availability', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('book_url', models.URLField(max_length=500, unique=True)),
                ('image_url', models.URLField(max_length=500)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
